package me.nebula.orbit.utils.mapgen

import me.nebula.orbit.utils.biome.BiomePresets

object MapPresets {

    operator fun get(name: String): MapGenerationConfig = when (name.lowercase()) {
        "perfect", "battleroyale" -> battleRoyale()
        else -> throw IllegalArgumentException("Unknown map preset: $name")
    }

    fun battleRoyale(seed: Long = System.currentTimeMillis()) = MapGenerationConfig(
        seed = seed,
        mapRadius = 250,
        terrain = TerrainConfig(
            seaLevel = 62,
            bedrockHeight = 1,
            fillerDepth = 3,
            deepslateLevel = 8,
            beachesEnabled = true,
            terrainScale = 0.008,
            continentalScale = 0.0015,
            continentalInfluence = 18.0,
            erosionScale = 0.004,
            erosionStrength = 0.35,
            riversEnabled = true,
            riverScale = 0.003,
            riverThreshold = 0.018,
            riverDepth = 3,
            riverWidth = 0.025,
            overhangsEnabled = true,
            overhangScale = 0.025,
            overhangThreshold = 0.5,
        ),
        biomeZones = BiomeZoneConfig(
            biomeScale = 0.0025,
            blendRadius = 12,
            fallbackBiomeId = "plains",
        ),
        caves = CaveConfig(
            enabled = true,
            wormsPerChunk = 3,
            wormFrequency = 0.5,
            wormMinLength = 50,
            wormMaxLength = 180,
            wormMinRadius = 1.5,
            wormMaxRadius = 4.5,
            wormMinY = 8,
            wormMaxY = 56,
            ravinesEnabled = true,
            ravineFrequency = 0.03,
            ravineMinLength = 70,
            ravineMaxLength = 220,
            ravineMinRadius = 1.0,
            ravineMaxRadius = 3.5,
            ravineVerticalStretch = 3.0,
            ravineMinY = 15,
            ravineMaxY = 65,
            roomsEnabled = true,
            roomFrequency = 0.08,
            roomMinRadius = 5.0,
            roomMaxRadius = 10.0,
            roomMinY = 10,
            roomMaxY = 42,
            lavaLevel = 10,
            bedrockFloor = 1,
            decorationEnabled = true,
            mossEnabled = true,
            glowLichenEnabled = true,
            dripstoneEnabled = true,
            hangingRootsEnabled = true,
            aquifersEnabled = true,
            aquiferMaxY = 32,
            aquiferThreshold = 0.28,
        ),
        ores = OreConfig(
            enabled = true,
            globalMultiplier = 1.3,
            veins = listOf(
                OreVeinConfig(net.minestom.server.instance.block.Block.COAL_ORE, 5, 128, 17, 22),
                OreVeinConfig(net.minestom.server.instance.block.Block.IRON_ORE, 5, 64, 9, 25),
                OreVeinConfig(net.minestom.server.instance.block.Block.GOLD_ORE, 5, 32, 9, 4),
                OreVeinConfig(net.minestom.server.instance.block.Block.DIAMOND_ORE, 5, 16, 8, 2),
                OreVeinConfig(net.minestom.server.instance.block.Block.REDSTONE_ORE, 5, 16, 8, 8),
                OreVeinConfig(net.minestom.server.instance.block.Block.LAPIS_ORE, 5, 32, 7, 2),
                OreVeinConfig(net.minestom.server.instance.block.Block.EMERALD_ORE, 5, 32, 1, 1),
                OreVeinConfig(net.minestom.server.instance.block.Block.COPPER_ORE, 5, 96, 10, 8),
            ),
        ),
        modifiers = ModifierConfig(
            enabled = true,
            iceOnFrozenWater = true,
            snowOnCold = true,
            surfacePatchesEnabled = true,
            patchScale = 0.08,
            patchThreshold = 0.55,
            coarseDirtPatches = true,
            gravelPatches = true,
            podzolPatches = true,
            clayUnderwaterEnabled = true,
            iceSpikesEnabled = true,
        ),
        population = PopulationConfig(
            treesEnabled = true,
            vegetationEnabled = true,
            bouldersEnabled = true,
            boulderChance = 0.025,
            pondsEnabled = true,
            pondChance = 0.01,
            mushroomsEnabled = true,
            underwaterVegetationEnabled = true,
            sugarCaneEnabled = true,
            cactusEnabled = true,
            lilyPadsEnabled = true,
            tallPlantsEnabled = true,
            fallenLogsEnabled = true,
        ),
        customBiomes = BiomePresets.all(),
    )
}
