package me.nebula.orbit.mutator

import me.nebula.ether.utils.translation.asTranslationKey

object MutatorDefinitions {

    val ALL: List<Mutator> = listOf(
        Mutator(
            id = "low_gravity",
            nameKey = "orbit.mutator.low_gravity.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.low_gravity.desc".asTranslationKey(),
            material = "minecraft:feather",
            overrides = mapOf("gravity" to mapOf("multiplier" to 0.4)),
            random = true,
            weight = 2,
        ),
        Mutator(
            id = "speed",
            nameKey = "orbit.mutator.speed.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.speed.desc".asTranslationKey(),
            material = "minecraft:sugar",
            overrides = mapOf("movement" to mapOf("speedMultiplier" to 1.5)),
            conflictGroup = "speed",
            random = true,
            weight = 2,
        ),
        Mutator(
            id = "double_speed",
            nameKey = "orbit.mutator.double_speed.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.double_speed.desc".asTranslationKey(),
            material = "minecraft:sugar",
            overrides = mapOf("movement" to mapOf("speedMultiplier" to 2.0)),
            conflictGroup = "speed",
        ),
        Mutator(
            id = "no_fall",
            nameKey = "orbit.mutator.no_fall.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.no_fall.desc".asTranslationKey(),
            material = "minecraft:leather_boots",
            overrides = emptyMap(),
            disables = setOf("fall-damage"),
            random = true,
            weight = 2,
        ),
        Mutator(
            id = "double_damage",
            nameKey = "orbit.mutator.double_damage.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.double_damage.desc".asTranslationKey(),
            material = "minecraft:netherite_sword",
            overrides = mapOf("damage-integration" to mapOf("damageMultiplier" to 2.0)),
            conflictGroup = "damage",
        ),
        Mutator(
            id = "half_damage",
            nameKey = "orbit.mutator.half_damage.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.half_damage.desc".asTranslationKey(),
            material = "minecraft:shield",
            overrides = mapOf("damage-integration" to mapOf("damageMultiplier" to 0.5)),
            conflictGroup = "damage",
            random = true,
        ),
        Mutator(
            id = "no_regen",
            nameKey = "orbit.mutator.no_regen.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.no_regen.desc".asTranslationKey(),
            material = "minecraft:poisonous_potato",
            overrides = emptyMap(),
            disables = setOf("natural-regen"),
            conflictGroup = "regen",
        ),
        Mutator(
            id = "fast_regen",
            nameKey = "orbit.mutator.fast_regen.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.fast_regen.desc".asTranslationKey(),
            material = "minecraft:golden_apple",
            overrides = mapOf("natural-regen" to mapOf("regenInterval" to 20, "regenAmount" to 1.0)),
            conflictGroup = "regen",
            random = true,
        ),
        Mutator(
            id = "turbo_loot",
            nameKey = "orbit.mutator.turbo_loot.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.turbo_loot.desc".asTranslationKey(),
            material = "minecraft:chest",
            overrides = mapOf("chest-loot" to mapOf("quantityMultiplier" to 2.0)),
            random = true,
            weight = 2,
        ),
        Mutator(
            id = "no_hunger",
            nameKey = "orbit.mutator.no_hunger.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.no_hunger.desc".asTranslationKey(),
            material = "minecraft:cooked_beef",
            overrides = emptyMap(),
            disables = setOf("hunger"),
            random = true,
        ),
        Mutator(
            id = "explosive_arrows",
            nameKey = "orbit.mutator.explosive_arrows.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.explosive_arrows.desc".asTranslationKey(),
            material = "minecraft:tnt",
            overrides = mapOf("projectiles" to mapOf("explosionPower" to 2.0)),
        ),
        Mutator(
            id = "one_hit",
            nameKey = "orbit.mutator.one_hit.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.one_hit.desc".asTranslationKey(),
            material = "minecraft:diamond_sword",
            overrides = mapOf("damage-integration" to mapOf("damageMultiplier" to 999.0)),
            conflictGroup = "damage",
        ),
        Mutator(
            id = "random_kits",
            nameKey = "orbit.mutator.random_kits.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.random_kits.desc".asTranslationKey(),
            material = "minecraft:ender_chest",
            overrides = mapOf("__gamemode__" to mapOf("randomKits" to true)),
        ),
        Mutator(
            id = "fast_zone",
            nameKey = "orbit.mutator.fast_zone.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.fast_zone.desc".asTranslationKey(),
            material = "minecraft:magenta_glazed_terracotta",
            overrides = mapOf("__gamemode__" to mapOf("zoneShrinkMultiplier" to 2.0)),
            conflictGroup = "zone",
        ),
        Mutator(
            id = "slow_zone",
            nameKey = "orbit.mutator.slow_zone.name".asTranslationKey(),
            descriptionKey = "orbit.mutator.slow_zone.desc".asTranslationKey(),
            material = "minecraft:blue_ice",
            overrides = mapOf("__gamemode__" to mapOf("zoneShrinkMultiplier" to 0.5)),
            conflictGroup = "zone",
            random = true,
        ),
    )
}
